#!/usr/bin/env bash

if [[ $MANGO_TOOLCHAIN -ne 1 ]]; then
    echo "Not using toolchain, exiting..."
    exit 1
fi

CFLAGS="-std=gnu99 -ffreestanding -O2 -g -Wall -Wextra -fstack-protector"

DIR="$(mktemp -t mango.XXXX -d)"
CRTI="$DIR/crti.o"
CRTN="$DIR/crtn.o"
CRTBEGIN="toolchain/lib/gcc/i686-elf/$(i686-elf-gcc -dumpversion)/crtbegin.o"
CRTEND="toolchain/lib/gcc/i686-elf/$(i686-elf-gcc -dumpversion)/crtend.o"

compile() {
    # kernel souce compile
    echo "Compiling $1..."
    out=$(echo "$1" | sed 's|^src/||; s|\.c$|.o|')
    i686-elf-gcc -c $1 -Iinclude -o $DIR/$out $CFLAGS
    OBJECTS="$OBJECTS $DIR/$out"
}

assemble() {
    echo "Compiling $1..."
    out=$(echo "$1" | sed 's|^src/||; s|\.s$|.o|')
    i686-elf-as $1 -o $DIR/$out

    if [ "$out" != "crti.o" ] && [ "$out" != "crtn.o" ]; then
        OBJECTS="$OBJECTS $DIR/$out"
    fi
}

for asm in $(find src -name "*.s"); do
    assemble $asm;
done

for kernel_src in $(find src -name "*.c"); do
    compile $kernel_src;
done

echo "Objects ($OBJECTS)"
echo "Linking kernel..."
i686-elf-gcc -T src/linker.ld -o mango.bin -nostdlib \
    $CFLAGS $CRTI $CRTBEGIN $OBJECTS $CRTEND $CRTN -lgcc

if [[ $? -ne 0 ]]; then
    exit 1
fi

if [[ -f mango.bin ]]; then
echo "Building iso..."
mkdir -p $DIR/iso/boot/grub
cp mango.bin $DIR/iso/boot/
cat > $DIR/iso/boot/grub/grub.cfg << EOF
set timeout=0
set default=0

menuentry "Mango" {
    multiboot /boot/mango.bin
    boot
}
EOF
grub-mkimage -O i386-pc \
    -o $DIR/iso/boot/grub/_core.img \
    -p /boot/grub \
    multiboot biosdisk iso9660
cat /usr/lib/grub/i386-pc/cdboot.img $DIR/iso/boot/grub/_core.img > $DIR/iso/boot/grub/core.img
rm $DIR/iso/boot/grub/_core.img
xorriso -as mkisofs \
    -b boot/grub/core.img \
    -no-emul-boot \
    -boot-load-size 4 \
    -boot-info-table \
    -o mango.iso \
    -R $DIR/iso > /dev/null 2>&1
fi

echo "Done! cleanup..."
rm -r $DIR
