#!/usr/bin/env bash

DIR="$(mktemp -t mango.XXXX -d)"
OBJECTS="$DIR/boot.o" # assume bootloader will compile successfully

compile() {
    # kernel souce compile
    echo "Compiling $1..."
    out=$(echo "$1" | sed 's|^src/||; s|\.c$|.o|')
    i686-elf-gcc -c $1 -Iinclude -o $DIR/$out -std=gnu99 -ffreestanding -O2 -Wall -Wextra
    OBJECTS="$OBJECTS $DIR/$out"
}

i686-elf-as src/boot.s -o $DIR/boot.o
for kernel_src in $(find src -name "*.c"); do
    compile $kernel_src;
done
i686-elf-gcc -T src/linker.ld -o $DIR/mango.bin -ffreestanding -O2 -nostdlib $OBJECTS -lgcc

mkdir -p $DIR/iso/boot/grub
cp $DIR/mango.bin $DIR/iso/boot/
cat > $DIR/iso/boot/grub/grub.cfg << EOF
menuentry "Mango" {
    multiboot /boot/mango.bin
}
EOF
grub-mkrescue -o mango.iso $DIR/iso

rm -r $DIR
