#!/usr/bin/env bash

if [[ "$1" == "fresh" ]]; then
	rm disk.img
fi

test -f disk.img || ./build disk
qemu-system-i386 \
	-m 16M \
	-display gtk,zoom-to-fit=on,grab-on-hover=on \
	-boot d \
	-cdrom mango.iso \
	-audiodev alsa,id=snd0 -device ac97,audiodev=snd0 \
	-drive file=disk.img,format=raw \
	-netdev user,id=net0 \
	-device rtl8139,netdev=net0 \
	-serial stdio -s
