#!/usr/bin/env bash

test -f disk.img || ./build disk
qemu-system-i386 \
	-m 16M \
	-display gtk,zoom-to-fit=on,grab-on-hover=on \
	-boot d \
	-cdrom mango.iso \
	-audiodev alsa,id=snd0 -device ac97,audiodev=snd0 \
	-drive file=disk.img,format=raw \
	-netdev bridge,id=net0,br=virbr0 \
	-device ne2k_pci,netdev=net0 \
	-serial stdio -s $@
